config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
resources :restaurants

  root 'restaurants#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
 mount_uploader :photo, PhotoUploader 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
	def index
      @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find params[:id]
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new restaurant_params
  if @restaurant.save
        redirect_to @restaurant
    else
      render action: 'new'
    end
  end

  def edit
    @restaurant = Restaurant.find params[:id]
  end

  def update
    @restaurant = Restaurant.find params[:id]

    if @restaurant.update restaurant_params
      redirect_to @restaurant
    else
      render action: 'edit'
    end
  end

  def destroy
    @restaurant = Restaurant.find params[:id]
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :description, :phone, :address, :photo)
  end
end  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reserveste</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant, multipart: true) do |f| %>
  <% if @restaurant.errors.any? %>
    <div>
      <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% @restaurant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :name %>
  <%= f.text_field :name %>
  <br />

  <%= f.label :photo %>
  <%= image_tag(@restaurant.photo_url) if @restaurant.photo? %>
  <%= f.file_field :photo%>
  <%= f.hidden_field :photo_cache %>
  <br />

  <%= f.label :description %>
  <%= f.text_area :description %>
  <br />

  <%= f.label :phone %>
  <%= f.text_field :phone %>
  <br />

  <%= f.label :address %>
  <%= f.text_area :address%>
  <br />

  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing <%= @restaurant.name %></h1>

<%= render 'form' %>

app/views/restaurants/index.html.erb
<div class="row">
  <h1>
    Restaurants
    <span class="pull-right">
      <%= link_to new_restaurant_path, class: 'btn btn-default' do %>
        <i class="icon-plus-sign"></i> Add a Restaurant
      <%- end %>
    </span>
  </h1>
</div>

<ul class="thumbnails">
  <%- @restaurants.each do |restaurant| %>
    <li class="span3">
      <%= link_to restaurant do %>
        <div class="thumbnail">
          <img src="<%= restaurant.photo.thumbnail.url %>" alt="">
          <h3><%= restaurant.name %></h3>
        </div>
      <%- end %>
    </li>
  <%- end %>
</ul>

app/views/restaurants/new.html.erb
<h1>Add a Restaurant</h1>

<%= render 'form' %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>

<img src="<%= @restaurant.photo.masthead.url %>" />

<p><%= @restaurant.description %></p>

<dl>
  <dt>Phone</dt><dd><%= @restaurant.phone %>
  <dt>Address</dt><dd><%= @restaurant.address %>
</dl>

<ul>
  <li><%= link_to 'Edit', edit_restaurant_path(@restaurant) %></li>
  <li><%= link_to 'Remove', restaurant_path(@restaurant), method: :delete %></li>
</ul>